### ISSUE TITLE
Add new site Yosilo.se

### ISSUE THREAD

**Issue by toloco** [twbs/bootstrap-expo#1274]
Add new site Yosilo.se http://yosilo.se

**Comment by mdo** [comment]
Broken link it appears.

**Comment by toloco** [comment]
Man it isnt broken, please double check it

**Comment by mdo** [comment]
Ah, it doesn't work without the `www`—which I think you just added. Taking another look, we'll pass for now. Thanks though!

**Comment by toloco** [comment]
Sorry about that mate, actually it works with middle button click, weird isn't it?
