### ISSUE TITLE
ishouvik.com - Site Suggestion For Bootstrap Expo

### ISSUE THREAD

**Issue by ishouvik** [twbs/bootstrap-expo#1420]
<a target="_blank" href="http://ishouvik.com">iShouvik.com</a> is a Wordpress site created with Twitter Bootstrap as a child theme to my <a target="_blank" href="https://github.com/ishouvik/ishouvik-wp">Wordpress Twitter Bootstrap Skeleton Theme</a>.

**Comment by mdo** [comment]
Link is broken.

**Comment by ishouvik** [comment]
Hi,
It must have been a temporary glitch. http://ishouvik.com loads well now.
