### ISSUE TITLE
iamKevinRhodes.com Personal Portfolio Site

### ISSUE THREAD

**Issue by iamkevinrhodes** [twbs/bootstrap-expo#1436]
iamKevinRhodes.com is an elegant yet bold single page style site built on Bootstrap 3 and Wordpress. It’s designed by me, for me.

I designed the site to be agency style, with tons of bells and whistles, and took six months of my spare time :)

As the site says...

I designed this site so you can get to know me on a personal level. My career as a UX Designer, my portfolio, my personal photography, my blog, my favorite quotes, and so much more. So please sit back and enjoy!

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
