### ISSUE TITLE
Firebrick UI - Bootstrap Component Library

### ISSUE THREAD

**Issue by smasala** [twbs/bootstrap-expo#1444]
Resource: an open source JavaScript component library built with Bootstrap 3.

http://www.firebrickjs.com
http://www.github.com/smasala/firebrick.ui

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by smasala** [comment]
For reference, component library showcase/kitchen sink

http://www.firebrickjs.com/#/components

**Comment by smasala** [comment]
@mdo the framework has come some way since my initial comment. We support almost all BS3 components now. Everything from grid layouts, accordions, tabs, panels, modal to input fields, everything that is required to create rich responsive bootstrap based web applications.

http://firebrickjs.com/components
