### ISSUE TITLE
Extra

### ISSUE THREAD

**Issue by agtuks** [twbs/bootstrap-expo#1475]
Bootstrap and jQuery UI extra components: container sizes, dropdown to left and right, dropdown on hover, mega menu, nav tabs left, right and bottom, navbar static bottom, text helpers, brand colors, jQuery UI autocomplete bootstrap design, jQuery UI autocomplete ajax and many more. http://agtuks.github.io/extra/

**Comment by mugukamil** [comment]
@alextarkhov where it's now?
