### ISSUE TITLE
www.allmedialab.nl website built with Bootstrap 3 and Ajaxify implemented

### ISSUE THREAD

**Issue by Allmedialab** [twbs/bootstrap-expo#1496]
http://www.allmedialab.nl

Hi,

We have built our website with Bootstrap 3 and implemented a modern Ajax approach in to it named Ajaxify the jQuery Plugin from http://4nf.org . 
It's fine tuned for use in Bootstrap and to suit our personal needs. Notice the exceptional smooth behaviour of the content load and internal links. 
In cooperation with Arvind Gupta the founder of this awesome script we managed to create something special!
Images have been made responsive with: http://adaptive-images.com/
What do you think?

Regards,

David Akinci

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
