### ISSUE TITLE
Political science lab website : Triangle

### ISSUE THREAD

**Issue by samsaidi** [twbs/bootstrap-expo#1499]
http://triangle.ens-lyon.fr/

Graphic design : Peter Mepa - peter.mepa [at] live.fr

Front End development : Samantha Saïdi - samantha.saidi [at] gmail.com & Carole Boulai carole.boulai [at] ish-lyon.cnrs.fr

Architecture & Editorial work : Samantha Saïdi, Carole Boulai, Cécile Laube

CMS : SPIP http://www.spip.net/

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
