### ISSUE TITLE
Submit Site and Complaint

### ISSUE THREAD

**Issue by apollov** [twbs/bootstrap-expo#1502]
I'd like to submit a site, and complain about your policy of only having sites that look like Bootstrap.

First, I want to say how grateful I am that you've developed Bootstrap. I started an education company in 2011, and writing software is a small, but important part. Bootstrap made it possible for me to bootstrap. Our students use every kind of device. This cost of hiring a mobile developer would have sunk our thriving project. 

I would like to submit our site, www.seedlesson.com, which looks very much like Bootstrap. We couldn't make it better. Most students use our service through devices with limited data plans, and you had the best documented way of minimizing size. Bootstrap is the the most flexible grid, and allows me to layout information in a way that students new to technology can quickly grasp.

You all are brilliant for making this, and I am very grateful it is being maintained so well!

**Comment by mdo** [comment]
Aww <3.

Do you have any stand-out pages on the site? As it stands, the site is pretty streamlined. It looks great and feels fast, but it doesn't showcase a ton of Bootstrap after a quick perusal. Any thoughts?

**Comment by apollov** [comment]
Our clients are students, many who are just learning English, or who don't have internet access on a regular basis. It's dead simple on purpose.
We couldn't have done it without bootstrap (and font awesome, jquery, etc.)!

**Comment by mdo** [comment]
Good to hear! The site looks great, but it's not exactly what I'm trying to show folks in the Expo. For now, we'll pass on showcasing it. Keep up the good work though—it looks great!
