### ISSUE TITLE
DevFreeCasts and DevFreeBooks

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [twbs/bootstrap-expo#1509]
Hi, These are my projects, both using bootstrap with bootflat theme.

DevFreeCasts - A huge collection of free screencasts for developers (http://devfreecasts.org)
DevFreeBooks - A huge collection of free books for developers (http://devfreebooks.org)

I hope you enjoy and publish them into Bootstrap Expo

Thanks!

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
