### ISSUE TITLE
Submission of new website: Meta Box

### ISSUE THREAD

**Issue by rilwis** [twbs/bootstrap-expo#1514]
Website URL: [http://metabox.io](http://metabox.io)

This website uses a customisable version of Bootstrap with Google Fonts (with big font size for better readability and `rem` unit for better font scale). It also uses ghost buttons, custom style for hero area, product grid, documentation page and blog page.

This website is built with WordPress.

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
