### ISSUE TITLE
Metronic Theme Suggestion

### ISSUE THREAD

**Issue by shuxer** [twbs/bootstrap-expo#1517]
Hi :),

Seems some premium themes(with direct links) are being listed under resources.  
If possible could you please consider Metronic theme as well ?

Metronic - Multipurpose Bootstrap Admin Theme

Site: http://www.keenthemes.com/preview/

Ref: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes

Many thanks!

**Comment by mdo** [comment]
We might add it to the resources page, but that'd be it for now. Thanks though!
