### ISSUE TITLE
SmartAdmin - Responsive WebApp

### ISSUE THREAD

**Issue by sunnyat** [twbs/bootstrap-expo#1518]
I am the author of SmartAdmin. SmartAdmin is built with Bootstrap 3.3.1 and has its root designed based on Bootstrap's key features. I hope that the quality of SmartAdmin is good enough to be on your bootstrap-expo, it would be a dream come true and would be a nice addition to my resume! 

Live preview: http://192.241.236.31/themes/preview/smartadmin/1.5/ajaxversion/#ajax/dashboard.html

Kind regards,
Sunnyat Ahmmed

**Comment by mdo** [comment]
We're not showcasing themes just yet, but thanks for sharing!
