### ISSUE TITLE
VisitAbanoMontegrotto

### ISSUE THREAD

**Issue by ste93cry** [twbs/bootstrap-expo#1524]
[https://www.visitabanomontegrotto.com](https://www.visitabanomontegrotto.com)

A website promoting Abano Montegrotto and its SPA

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by ste93cry** [comment]
Thank you for considering the site, just one suggestion: as a user, it would be cool to have some sort of guidelines of what you look at to decide whether or not adding something to the EXPO
