### ISSUE TITLE
SMU Football

### ISSUE THREAD

**Issue by blake-athleticoffice** [twbs/bootstrap-expo#1538]
http://www.ponyuptempo.com/

**Comment by mdo** [comment]
I don't see much Bootstrap in this.

**Comment by blake-athleticoffice** [comment]
Not sure how you can say that... It's built entirely with Bootstrap. But ok. 

Blake E. Smith II
Founder/President 
AthleticOffice.com

**Comment by mdo** [comment]
Ah, you're right. Sorry about that! Took another look in the inspector and found all the nested rules in one of the several CSS files you have. I'll take another look at the design soon.

**Comment by blake-athleticoffice** [comment]
No problem! Sorry... we just use bootstrap pretty religiously. The only thing I could possibly see is some of the JavaScript not used. It's because we build sites on Liferay and pretty much forced to use their AlloyUI. Thanks for the reply. 

Blake E. Smith II
Founder/President 
AthleticOffice.com

**Comment by mdo** [comment]
That's awesome to hear! Taking another look at the site, I think we'll pass for now. It looks pretty solid though, so keep it up!

<3

**Comment by blake-athleticoffice** [comment]
Thanks anyway.

On Wed, Feb 18, 2015 at 4:55 PM, Mark Otto <notifications@github.com> wrote:

> That's awesome to hear! Taking another look at the site, I think we'll
> pass for now. It looks pretty solid though, so keep it up!
>
> <3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap-expo/issues/1538#issuecomment-74966350>
> .
>



-- 
Blake E. Smith II
AthleticOffice.com
970.988.4381 (mobile)
800.455.0967 (office)
