### ISSUE TITLE
Submission of www.coding-pioneers.com

### ISSUE THREAD

**Issue by apprecht** [twbs/bootstrap-expo#1561]
Hello Mark,
I would like to submit our new website http://www.coding-pioneers.com/ to the bootstrap-expo.

The guidelines I found very useful and they should be complied. The Output of the site is minifyed so the markup ist't that readable anymore.

If there are any issues I'll try to resolve them.

Thanks so far,
Sebastian

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
