### ISSUE TITLE
Site suggestion: Geo for Bootstrap, a Timeless Theme by Divshot

### ISSUE THREAD

**Issue by Lisa-Williams** [twbs/bootstrap-expo#1563]
Just bumped into this one. Submitting it just for fun.
Built on Bootstrap v2.3.1

[http://code.divshot.com/geo-bootstrap/](http://code.divshot.com/geo-bootstrap/)

As per your submission requirements, it's a high quality, beautiful, and comprehensive example of late 20th century, early 21st century style building with Bootstrap. The site absolutely does not appear too similar to Bootstrap’s documentation or default styles. And it doesn't contain inappropriate content.

![geo-for-bootstrap_2015-02-28_20-53-39](https://cloud.githubusercontent.com/assets/6225311/6427859/a9a83356-bf8d-11e4-9af9-b24b3a1e176a.png)

**Comment by mdo** [comment]
Been aware of this one for awhile now—definitely one of my favorites :).
