### ISSUE TITLE
Florida DreamCenter

### ISSUE THREAD

**Issue by AustinCline88** [twbs/bootstrap-expo#1565]
Please consider floridadreamcenter.org for the Bootstrap Expo. 

With love. 
![florida_dreamcenter](https://cloud.githubusercontent.com/assets/9614546/6433457/aa4e415a-c03d-11e4-9982-7767c9da81f7.png)

![screen shot 2015-03-01 at 6 06 31 pm](https://cloud.githubusercontent.com/assets/9614546/6433462/bde00ef6-c03d-11e4-8de5-3076c8fe610d.png)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
