### ISSUE TITLE
Santander Bank AS

### ISSUE THREAD

**Issue by M33Media** [twbs/bootstrap-expo#1571]
Hi! Since last year we built a new website for our company. It's built on top of Sharepoint(That wasn't easy) But we ended up with a website that has been rewarded as the most innovative in this this business. Have a look!! https://www.santanderconsumer.no
![santander front](https://cloud.githubusercontent.com/assets/6738368/6491814/30e9e9de-c2b0-11e4-8480-1013c8bdb4b4.jpg)
![santander calculator](https://cloud.githubusercontent.com/assets/6738368/6491817/32e9e356-c2b0-11e4-862f-8b2651381702.jpg)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
