### ISSUE TITLE
STI 31st Anniversary Website

### ISSUE THREAD

**Issue by dengbalaga** [twbs/bootstrap-expo#1577]
STI 31st Anniversary Website

This year, STIers will unite to honor its own heroes: the empowered students, faculty members, staff, and alumni worldwide who are heroes in their own right. They are the champions of their own cause, unafraid to take action and realize positive change.

For the 31st Anniversary, STI continues to take a step towards building a nation of heroes. Dare to unleash the hero in you and join the league of empowered citizens who are the hope of a better nation.

Be your own hero. Be STI!

http://anniversary.sti.edu

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
