### ISSUE TITLE
Maps.to - Unique Link & QR Code Generator

### ISSUE THREAD

**Issue by kaushalpanchal** [twbs/bootstrap-expo#1590]
### www.maps.to Single QR Code and link for all platforms for free

Generate a single QR code and link for iPhone, Android, Windows, Blackberry, Amazon Kindle Apps & web. Analyze usage and generate unlimited QR codes for free.

![maps to](https://cloud.githubusercontent.com/assets/9069080/6570277/aa2a916a-c71d-11e4-83bc-475088d35c0d.png)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
