### ISSUE TITLE
New ecommerce site built with Bootstrap

### ISSUE THREAD

**Issue by arnaudleyder** [twbs/bootstrap-expo#1594]
Hi, 

I have released a new ecommerce site based on bootstrap: https://www.alombredutheier.bio
Yes it is in French, so you might not understand everything but I hope the design is cool enough. 

You can also check https://www.radiantmediaplayer.com which I also built with bootstrap. This one is in full English.

Thanks for your time.
Arnaud

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
