### ISSUE TITLE
WordPress Knowledge Base Theme

### ISSUE THREAD

**Issue by swashata** [twbs/bootstrap-expo#1595]
I made a free Knowledge Base theme using bootstrap. Theme is at WordPress repository: https://wordpress.org/themes/wp-knowledge-base/ and also at github https://github.com/swashata/ipt-knowledgebase-theme-wp

An example and also our live Knowledge Base over here: http://ipanelthemes.com/kb/

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
