### ISSUE TITLE
Leung Enterprises Official Site

### ISSUE THREAD

**Issue by LeungEnterprises** [twbs/bootstrap-expo#1596]
Though it is my website, it still looks pretty cool (at least to me) and I think it would be great if it could be put into the expo!

Check it out at http://leung.enterprises/

Thanks

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by LeungEnterprises** [comment]
Hi @mdo,

I made a major update to the site aesthetic, and if you could check it out one more time and give me some feedback on the design that would be awesome (and greatly appreciated).  Thank you!

http://leung.enterprises/

![Leung Enterprises](http://i.imgur.com/LRl8J2j.jpg)
