### ISSUE TITLE
Site Suggestion: cycleplan

### ISSUE THREAD

**Issue by gahmad** [twbs/bootstrap-expo#1608]
http://www.insure4sport.co.uk/cycleplan/

The site has been launched today and  is built with Bootstrap 3 as a platform. The following web technologies have been used to deliver this responsive website:

1) HTML5
2) CSS3
3) Javascript
4) JQuery
5) AJAX
6) ASP.NET

ABOUT THE COMPANY

cycleplan is specialist cycling insurance from insure4sport, one of the UK’s leading sport insurers. The team behind cycleplan recognised the limitations of many household insurance policies in terms of covering cyclists, their bicycles and accessories. We created comprehensive cycling insurance that can be tailor-made to suit your individual needs. We cover most kind of cyclist, giving peace of mind each time you get on the saddle. Reliable, low-cost and designed so that cyclists only pay for the cover they need, cycleplan has established itself as one of the leading cycling insurance providers in the UK.

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
