### ISSUE TITLE
www.designtribe.ie

### ISSUE THREAD

**Issue by DesignGuyIreland** [twbs/bootstrap-expo#1612]
Hi,

I have a new responsive site up based on the bootstrap3 framework,  it validates as compliant with W3C.  

The site represent me a one man web dev 'team', I would love the exposure :-)  
http://www.designtribe.ie/

Thanks for your time,
Ivan

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by DesignGuyIreland** [comment]
Hi Mark

That's a Bootstrap v3.2.0  site,   that uses the .col-md-pull- / push
modifier classes.

I've tried  hard to avoid the now standardized bootstrap layout, I was
hoping that would get it a second look.

Ivan
