### ISSUE TITLE
Residence Luna Cavtat

### ISSUE THREAD

**Issue by newPrimitives** [twbs/bootstrap-expo#1613]
Website for a luxury Villa in Cavtat, Croatia, built with Bootstrap fully responsive and compatible across all major browsers. link for the website: http://residenceluna.com
![luna1](https://cloud.githubusercontent.com/assets/3939242/6761529/90dd1d1a-cf54-11e4-9053-e7e73afd6937.png)
![luna2](https://cloud.githubusercontent.com/assets/3939242/6761531/90e19cd2-cf54-11e4-8c88-dd0a4d7434c4.png)
![luna3](https://cloud.githubusercontent.com/assets/3939242/6761530/90dfce52-cf54-11e4-9b22-84dc0ba16aea.png)
![luna4](https://cloud.githubusercontent.com/assets/3939242/6761532/90e3b49a-cf54-11e4-9ade-1ac8b11f0a83.png)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
