### ISSUE TITLE
STI College

### ISSUE THREAD

**Issue by dengbalaga** [twbs/bootstrap-expo#1614]
Hi, i'd like recommend our site made from bootstrap.
http://www.sti.edu/

Nature: Education / College
Company Site Description: One of the largest networks of schools in the Philippines. With its unique Enrollment to Employment System (E2E), STI continues to nurture globally competitive graduates in the fields of Information and Communications Technology, Tourism and Hospitality Management, Business and Management, Engineering, Arts and Sciences, and Healthcare
Developer: Dennis Balaga

![stiedu-printcreen1](https://cloud.githubusercontent.com/assets/10105074/6763222/62c6604e-cfae-11e4-95ff-59ebc101f6c9.jpg)
![stiedu-printcreen2](https://cloud.githubusercontent.com/assets/10105074/6763223/6ad041b0-cfae-11e4-9a34-a20da25c03fb.jpg)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
