### ISSUE TITLE
Azuax IT solutions

### ISSUE THREAD

**Issue by mirkocabello** [twbs/bootstrap-expo#1628]

**Comment by mdo** [comment]
No URL provided.

**Comment by mirkocabello** [comment]
http://www.azuax.com/

**Comment by mirkocabello** [comment]
Sorry for not provide the url but there it is , I would aprarecer in
bootstrap -expo but not well how to do it

thanks , greeting
http://www.azuax.com/

2015-03-30 16:10 GMT-03:00 Mark Otto <notifications@github.com>:

> No URL provided.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap-expo/issues/1628#issuecomment-87795003>
> .
>



-- 
*Mirko Cabello M.*
Estudiante de Ingeniería de Ejecución en Informática Mención Desarrollo de
Sistemas.
Instituto Profesional AIEP.

**Comment by mdo** [comment]
Thanks for providing the link—we'll pass for now though.

<3
