### ISSUE TITLE
Sidra Cortina

### ISSUE THREAD

**Issue by objetivocreativo** [twbs/bootstrap-expo#1642]
Suggested Project for the Expo
-
Project: www.sidracortina.com
Technology: Bootstrap
Author: Objetivo Creativo (www.objetivocreativo.com)
Spanish Web Agency

**Comment by objetivocreativo** [comment]
Suggested Project for the Expo
-
Project: www.ajeasturias.com
Technology: Bootstrap
Author: Objetivo Creativo (www.objetivocreativo.com)
Spanish Web Agency

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
