### ISSUE TITLE
Encarnación Expone

### ISSUE THREAD

**Issue by krugerdavid** [twbs/bootstrap-expo#1654]
Hello. I will like to propose the site http://encarnacionexpone.com/ 
Ombu, a small digital agency created the website for a startup summit on the South of Paraguay. 
Regards
![ee](https://cloud.githubusercontent.com/assets/467435/7031512/18d0b734-dd3a-11e4-9912-8ace370c8b17.jpg)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by krugerdavid** [comment]
Sure.. Why didn't classify? I'm asking to improve my upcoming works :)

**Comment by hisapy** [comment]
+1 for feedback to improve upcoming works @mdo
