### ISSUE TITLE
site suggestion

### ISSUE THREAD

**Issue by pmawebagency** [twbs/bootstrap-expo#1680]
we want to suggest piccolemedieaziende.it

thank you

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by pmawebagency** [comment]
WHY??? You little bitch!

 

:)

 

 

Da: Mark Otto [mailto:notifications@github.com] 
Inviato: lunedì 11 maggio 2015 22.59
A: twbs/bootstrap-expo
Cc: pmawebagency
Oggetto: Re: [bootstrap-expo] site suggestion (#1680)

 

Thanks, but we'll pass for now <3.
