### ISSUE TITLE
http://www.peoplespharmacy.com/

### ISSUE THREAD

**Issue by camelCase123** [twbs/bootstrap-expo#1702]
This site may not seem flashy but is a great example of a very functional website, with lots of text content, which seems to be less represented in the expo.  Also, it's very customized so it does not have a typical bootstrap feel to it, which is interesting. The site has nice transitions over links and nice navbar  The content has a nice structure for the articles.  Attractive footer too.
eg http://www.peoplespharmacy.com/home-remedies/in-the-kitchen/

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
