### ISSUE TITLE
suggested site Fleet Genius

### ISSUE THREAD

**Issue by JCollins-Prova** [twbs/bootstrap-expo#1712]
I'd like to suggest http://www.fleet-genius.com/ for your site.  We have a ruby-on-rails development using bootstrap in a 100% responsive design.  We have designed it to avoid the need for specialized apps for smartphone platforms.  

The system captures telematics data collected for fleet management.  We also support an API in the application for customers who want to export their data.  

Let me know if you have any questions.

Thanks

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
