### ISSUE TITLE
? - Bootstrap support

### ISSUE THREAD

**Issue by rwm70c** [twbs/bootstrap-expo#1723]
I know this question probably does not belong here but I can not figure out where to post it.  I am looking to see if anyone is aware of a company or resource that provides professional support to companies using BootStrap.  Not for design purposes, basically just serving as a resource for questions in the event issues do arise using the framework.  Ideally also recommending a specific version and build for use.

**Comment by mdo** [comment]
Might try asking in the official Slack team. Details for that are in Bootstrap's project readme.
