### ISSUE TITLE
SOLO

### ISSUE THREAD

**Issue by orlandotm** [twbs/bootstrap-expo#1730]
https://solo.sh/orlandotm

**Comment by mdo** [comment]
I see a payment page...

**Comment by orlandotm** [comment]
Yes, is the payment page of our virtual PoS called SOLO (www.solo.sh). You can see other examples here:

https://solo.sh/sakecompany
https://solo.sh/quitepeople
https://solo.sh/leogr

**Comment by mdo** [comment]
Word, thanks.

I could see maybe doing the product homepage, but not the individual payment profiles.

**Comment by orlandotm** [comment]
Thanks! We would like to show you that we're are doing with bootstrap. Is like Square Cash (Cash.me), but for european merchants. SOLO is the virtual POS that allows any merchant from the 23 countries in SEPA that adopt Euro as principal currency to accept credit and debit cards payments without having to swipe the card into a physical device, as the traditional POS does.

**Comment by mdo** [comment]
Going to punt on this one for a bit. Overall aesthetics are good and it's a bit tough to tell it's Bootstrap (yay!), but there's some missing polish (superfluous hyphenation, spatial alignment, etc). Happy to revisit if y'all make any tweaks around that stuff soon <3.
