### ISSUE TITLE
Suggested Sites to Include in Expo

### ISSUE THREAD

**Issue by welshfusion** [twbs/bootstrap-expo#1731]
Hi,

Here are 2 of the sites we've built on Bootstrap we are especially proud of so we wanted to see if we could get them included in the gallery:

http://enzoani.com/
http://www.iaith.cymru

If you could let me know if they get accepted that would be great!

Keep up the good work, we love using bootstrap!
Thanks,

Neil

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
