### ISSUE TITLE
Suggested submission for inclusion in the Bootstrap expo

### ISSUE THREAD

**Issue by bigprof** [twbs/bootstrap-expo#1763]
This is not strictly a "site", but a tool to build bootstrap-based web applications. The tool, AppGini, is a desktop application that empowers non-developers to create awesome looking responsive web applications for managing their data. They can select among 17 Bootstrap themes that come with AppGini. So, this is an application that enables the rest of the world to appreciate the beauty of Bootstrap and use it without having to learn all the tech details and jargon.

AppGini comes in 2 editions, a free limited trial, and a pro edition. Available from http://bigprof.com/appgini

**Here are some screenshots of applications created using AppGini**

*The login page*
![The login page](https://s3.amazonaws.com/appgini-desktop/images/screenshots/appgini-5.20-login-page.png)

*The main screen*
![The main screen](https://s3.amazonaws.com/appgini-desktop/images/screenshots/appgini-5.20-home-page.png)

*List view of one of the tables*
![List view of one of the tables](https://s3.amazonaws.com/appgini-desktop/images/screenshots/appgini-5.20-table-view.png)

*Images can be zoomed beautifully*
![Images can be zoomed beautifully](https://s3.amazonaws.com/appgini-desktop/images/screenshots/appgini-5.20-table-view-zoom-images.png)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
