### ISSUE TITLE
Just Gluten Free website submission

### ISSUE THREAD

**Issue by pedro1993** [twbs/bootstrap-expo#1767]
Hi guys!

I am Peter from CO2 design (www.co2design.co.uk). I came across the expo page on the website and thought I would share one of our Bootstrap websites we created for our client "Just Gluten Free"

Here is the website: http://www.justglutenfree.co.uk/

Thanks,
Peter

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
