### ISSUE TITLE
Haven Life Website for Expo Consideration

### ISSUE THREAD

**Issue by brittneyburgett** [twbs/bootstrap-expo#1775]
Hello -

I'd like for my company's website, https://havenlife.com, to be considered for the Bootstrap Expo. We've utilized your default style sheet and implemented our own UX to create a consumer friendly and mobile optimized site. We think you'll like what we've done.

For background, Haven Life is the first and only website to sell term life insurance online. The typical process takes 4 to 6 weeks and couldn't be accomplished online. We've created a site that provides an application and approval process that can start coverage in 20 minutes.

![haven-life-launch-home-page](https://cloud.githubusercontent.com/assets/9438085/7967533/9bb12630-09f8-11e5-8eea-c9bd69e5b391.jpeg)

If you have any questions, please email me: brittney@havenlife.com.

Thanks for your time and consideration,
Brittney

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by brittneyburgett** [comment]
Thanks for letting me know, and please keep us in mind!

On Fri, Jun 5, 2015 at 12:36 AM, Mark Otto <notifications@github.com> wrote:

> Thanks, but we'll pass for now <3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap-expo/issues/1775#issuecomment-109158671>
> .
>



-- 

Brittney Burgett
Marketing & Content Development Manager

O: 646-762-0295
brittney@havenlife.com
https://havenlife.com
