### ISSUE TITLE
Creative Tim: Presentation Page Redesign

### ISSUE THREAD

**Issue by alexandru-paduraru** [twbs/bootstrap-expo#1822]
http://demos.creative-tim.com/presentation

**Comment by mdo** [comment]
Hey there, looking good! Is this an actual page or simply an example of the Rubik theme?

**Comment by alexandru-paduraru** [comment]
Hi, we appreciate your feedback! 

It is the actual page that we send to non-technical persons (ex: Startup Weekends' organisers) or Backend developers (ex: guys who don't know web design but can use Bootstrap and our items) to understand what exactly is Creative Tim. 

We made it with Rubik because it was easier for us to use something that we already created.

**Comment by alexandru-paduraru** [comment]
Hey @mdo, any news on this?
