### ISSUE TITLE
Bootstrap Expo Site Suggestion

### ISSUE THREAD

**Issue by samblikArendus** [twbs/bootstrap-expo#1849]
Hello there!
Our company's <a href="http://firzen.eu/" target="_blank">website</a> was made using Bootstrap V3 and it be a great honor to have up on Bootstrap Expo. Here is <a href="http://firzen.eu/" target="_blank">our website</a>.

All the best!
The Firzen Team

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
