### ISSUE TITLE
Swan Gallery

### ISSUE THREAD

**Issue by olivier3lanc** [twbs/bootstrap-expo#1850]
Hi guys,

just another webdesigner that built an app with Bootstrap^^

![image](https://cloud.githubusercontent.com/assets/13103047/8478411/86a86aa6-20d1-11e5-89e8-40b8dd0abce4.png)

## Swan Gallery
A free web photo gallery for photographers and creatives. Swan Gallery is a web photo gallery application based on JPEG IPTC metadata and PHP. The script is thought to be as much “Hassle Free” as possible, very simple to install, use, backup and upgrade.
http://www.egalise.com/swan-gallery/

## Templates
http://www.egalise.com/swan-gallery/templates/

## Documentation
http://www.egalise.com/swan-gallery/documentation/

Thank you so much ;)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
