### ISSUE TITLE
BAMMA

### ISSUE THREAD

**Issue by martinbean** [twbs/bootstrap-expo#1859]
http://www.bamma.com

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by martinbean** [comment]
@mdo Any particular reason?

**Comment by mdo** [comment]
Overall it's a solid looking site. It doesn't show too much of Bootstrap in a unique way, despite not looking at all like Bootstrap (which is super awesome). It's hard to describe other than it's not something I want to showcase right now. That's more to do with the approach to the entire Expo than individual submissions (we've got some ideas on how to overhaul it soon).

There's also a small rendering error I just noticed—at the top some stuff is cut off in latest Safari.

**Comment by martinbean** [comment]
@mdo OK.

Thanks for the tip about the Safari issue but I can’t replicate it. What version of Safari are you using? It looks OK for me in 8.0.7.

**Comment by mdo** [comment]
Safari 9
