### ISSUE TITLE
http://gardahaus.it & http://midnightfactory.it

### ISSUE THREAD

**Issue by paolomarchettird** [twbs/bootstrap-expo#1862]
Hi, please consider adding http://gardahaus.it and http://midnightfactory.it , the last sites released by Riot Design, both made with Bootstrap Sass.

thanks

![gardahaus-expo](https://cloud.githubusercontent.com/assets/13290029/8634309/5d88f404-27f4-11e5-83a9-7a61959d6f55.jpg)
![midnightfactory-expo](https://cloud.githubusercontent.com/assets/13290029/8634310/5d8bf398-27f4-11e5-9d52-f53b4cdd54b6.jpg)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
