### ISSUE TITLE
Site suggestion - www.marktplatz-natur.de

### ISSUE THREAD

**Issue by 21cdb** [twbs/bootstrap-expo#1872]
EUROPARC Deutschland e.V., NGO for national parks in Germany uses bootstrap to build a marketplace for projects within the national parks that need founding. 
![marktplatz-natur de](https://cloud.githubusercontent.com/assets/13256287/8910827/4cfc2010-3489-11e5-89a2-408d1e519329.png)

**Comment by nicole** [comment]
Added Monday, August 24th, 2015.
