### ISSUE TITLE
Bootstrap Expo Submission

### ISSUE THREAD

**Issue by patrickording** [twbs/bootstrap-expo#1896]
https://www.dlv.de/

Hi!

My name is Patrick and I'm a frontend developer at a Munich based agency called https://www.schalk-and-friends.de/

I'd love to see our work we did for the "Deutscher Landwirtschaftsverlag" https://www.dlv.de/ in the Bootstrap Expo.

Take Care
Patrick

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
