### ISSUE TITLE
Suggest a site - https://cashkumar.com

### ISSUE THREAD

**Issue by yogeshsjoshi** [twbs/bootstrap-expo#1925]
Fintech startup based out of India, currently disrupting the way people get loans and other financial services. 
![screen shot 2015-08-25 at 7 44 30 pm](https://cloud.githubusercontent.com/assets/11755037/9468889/c4d74b20-4b61-11e5-93f4-73ef78de2adb.png)

https://cashkumar.com

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
