### ISSUE TITLE
Submit a site at http://expo.getbootstrap.com/

### ISSUE THREAD

**Issue by triplejweb** [twbs/bootstrap-expo#1936]
Hello. I want propose to visit a site after developed with Bootstrap . It would be great if it could be included in their directory.
thanks, regards

The site: www.triplejweb.cl
![captura de pantalla 2015-09-05 a las 13 38 09](https://cloud.githubusercontent.com/assets/3988459/9700649/d99d9b04-53e0-11e5-92fc-53eb5c577333.png)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
