### ISSUE TITLE
Expo suggestion

### ISSUE THREAD

**Issue by fpelosi** [twbs/bootstrap-expo#1940]
www.mybrandevolved.com

Thanks.

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.

**Comment by fpelosi** [comment]
Thanks for checking it out! Any suggestions (lacks animations, cleaner
code, looks to out-of-box)?

Thanks in advance,
Frank

On Mon, Sep 28, 2015 at 2:23 PM, Mark Otto <notifications@github.com> wrote:

> Thanks, but we'll pass for now <3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap-expo/issues/1940#issuecomment-143834028>
> .
>



-- 
*Frank Pelosi*
716.462.0199
pelosi.frank@gmail.com
