### ISSUE TITLE
Expo feature request

### ISSUE THREAD

**Issue by dylanvalade** [twbs/bootstrap-expo#1944]
https://www.redi-rock.com/concrete-blocks-reinforced-retaining-walls.htm

Bootstrap customizations:
- menus hide and show with scroll intent using headroom, logo changes
- Custom drop downs: support rows and columns, inline form in the Where To Buy menu dropdown (sm size and larger)
- responsive contact forms on Pardot.com (Salesforce) are also styled with Bootstrap and displayed with responsive iframes that automatically resize with form validation errors
- images lazy loaded with imgix Javascript API to match rendered element dimensions

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
