### ISSUE TITLE
Bootstrap Expo site suggestion

### ISSUE THREAD

**Issue by juansebas0712** [twbs/bootstrap-expo#1945]
Hello, I'm using bootstrap for all my projects but this is which i'm most proud of, my portfolio.

http://juansaparicio.com/

![portfolio](https://cloud.githubusercontent.com/assets/2074714/9741531/861f4a58-5620-11e5-9fff-c3b6583fac48.png)

**Comment by mdo** [comment]
Thanks, but we'll pass for now <3.
