### ISSUE TITLE
Add TwitchPoll to Bootstrap Expo

### ISSUE THREAD

**Issue by AuroraAri** [twbs/bootstrap-expo#2033]
TwitchPoll is a web service designed to help Twitch streamers poll their audience. It includes features that let streamers restrict voting to followers (people who just click the "follow" button), subscribers (paying members of a community), team members and even a whitelist of other Twitch users.

P.S. Bootstrap is awesome; thanks so much for it! <3

**Comment by Mortiferr** [comment]
https://www.twitchpoll.com is the link for those too lazy to Google it. I don't feel this is quite on par with the sites I've seen on /twbs/bootstrap-expo/. The one's I've seen on expo are mainly custom and different looking than the default Bootstrap. Great site though. But hey, I could be totally wrong.
