### ISSUE TITLE
Transferology.com and Transferologylab.com

### ISSUE THREAD

**Issue by hillgr** [twbs/bootstrap-expo#2042]
Hi,

I'd like to submit two websites to the expo that my company created using bootstrap:

www.transferology.com and www.transferologylab.com

Thanks

**Comment by haejinjo** [comment]
@hillgr  hi Greg, can I help in implementing a "filter by online course" feature for transferology.com? It's already a very useful site, and well-made, but this last filter step would've saved me that much more time.

Is the database queried using SQL?
