### ISSUE TITLE
Site Submission: Paytweak.com

### ISSUE THREAD

**Issue by Cetic91** [twbs/bootstrap-expo#2276]
**Paytweak.com** is a 30 days free website to Build your own Universal Secure Payment Links to get Payments in **seconds**, directly to your bank account with **No delay** and **No fees** ! It accept Wallets or Acquirers from more than **500 banks**. You can include **Team members** and get direct statistics from your team

**- It's up to 3 times cheaper**
Save on the fees and commissions charged on transactions by third parties
No more waiting for funds to be transferred to your bank account

**- EASY !**
Choose existing messages or create your owns. Fill the amount and the customer's e-mail address or mobile phone number and send the request through Paytweak or your usual softwares

**- FAST ! ...**
Customers receive secure messages via Paytweak, meaning they can clearly identify you and make payments in total confidence.

**- PROFITABLE !**
Payments comes directly in your bank account. You save on intermediaries' commissions and receive funds without delay.

**- Connect your apps and softwares through our powerful 99,9% SLA Rest API**
Trigger sophisticated payment requests anywhere, at anytime from/to any devices and get payments approval in seconds

**- Use all or some of PayTweak's features as a white label service.** 
The solution integrates perfectly with your business, simplifies your collection or that of your customers and can be fully redesigned using your colours. Our intuitive, well-documented Rest API means you can use the service on all your platforms: web app, mobile app, website or web service, etc

![image](https://cloud.githubusercontent.com/assets/27926528/25316424/559ee9ea-2867-11e7-8e6f-575f2648da0a.png)

![image](https://cloud.githubusercontent.com/assets/27926528/25316447/8b2359c0-2867-11e7-8bd1-8376260e189f.png)

![image](https://cloud.githubusercontent.com/assets/27926528/25316495/8f222668-2868-11e7-8c3d-45086156fc4a.png)

**Comment by probykam** [comment]
hello
