### ISSUE TITLE
Bootstrap Expo submission

### ISSUE THREAD

**Issue by BracketNerd101** [twbs/bootstrap-expo#2312]
Hello Bootstrap team, 

I have recently completed my portfolio website. I used the latest version, Bootstrap 4. I am really excited about this submission and I am officially would like to submit my code. 

My profile and code base of the portfolio website I would like to submit can be found in the link below. 

https://github.com/BracketNerd101/Jedi-Returns

you can find my portfolio website online at www.designbyarthur.com

Please let me know what else I need to do in the submittal process. 

All The Best, 

Arthur Charles Edwrds

**Comment by zoomla** [comment]
这个漂亮！
