### ISSUE TITLE
Suggestion: https://ReservarCannabis.com

### ISSUE THREAD

**Issue by jonasrafael** [twbs/bootstrap-expo#2336]
built with Bootstrap v4.0
and wordpress
90 of google page speed
tks

**Comment by bardiharborow** [comment]
Thanks, but we'll pass for now. <3

**Comment by jonasrafael** [comment]
Hello friends, a new version of the "Reservar Cannabis" is made with bootstrap 4 and is already notified in the largest vehicles in latin america. The application show the availability of state cannabis in pharmacies of Uruguay. (That's because in Uruguay, as pharmacies sell cannabis). This is the first country in the world that has legalized an herb for non-medicated fins.

The bootstrap is PWA application", developed in the first country in the world to legalize cannabis and sell in pharmacies.  The leading newspapers in Latin America have already talked about the application and are competing for an annual local award. It would be an honor to show gallery as case, because it shows how a boostrap can [help solve social problems](https://reservarcannabis.com/el-algoritmo-del-cannabis-como-surgio-el-reservar-cannabis/).

[El País - Aplicación acorta filas para compra de marihuana en las farmacias
](ttps://www.elpais.com.uy/vida-actual/aplicacion-acorta-filas-compra-marihuana-farmacias.html
)
[El Observador](https://www.elobservador.com.uy/nota/reserva-cannabis-una-app-para-eliminar-filas-en-farmacias--2019111919648)
